import os
def atoms2c(output,dx,dy,dz,x,y,z):
    with open(output, 'r') as f:
        # Read the lines from the file
        lines = f.readlines()
        atoms_number = lines[1]

    newgro = []
    f_name = output.removesuffix('.gro')+'_new.gro'
    with open(f_name, 'w') as fp:
        newgro.append("generated by MOF_BUILD"+'\n'+str(atoms_number))
        # Iterate over each line in the input file
        for i in range (2,len(lines)-1):
            # Split the line into individual values (assuming they are separated by spaces)
            #values = lines[i].split()
            value_resnumber = int((lines[i])[0:5])
            value_resname = lines[i][5:10]
            
            value_label = lines[i][10:15]
            value_atom_number = int(lines[i][15:20]) 
            value_x = float(lines[i][20:28])+dx #x      
            value_y = float(lines[i][28:36])+dy#y
            value_z = float(lines[i][36:44])+dz #z

            formatted_line = "%5d%-5s%5s%5d%8.3f%8.3f%8.3f" % (
                        value_resnumber, value_resname, value_label, value_atom_number, value_x, value_y, value_z
            )            
            newgro.append(formatted_line+'\n')
        
        box = str(x)+'   '+str(y)+'   '+str(z) + '\n'

        newgro.append(box)    
        fp.writelines(newgro)
        print(f_name,' is generated')
        return f_name
